name = "FASTQ"
uuid = "ee7f7801-48cc-40da-98c9-e39305ba84b2"
version = "0.1.0"
authors = ["KatharineME <katharine.me@icloud.com>"]

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
<<<<<<< HEAD
Omics = "55404059-57b2-473d-9cce-582834f19b54"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Dates = "1.11.0"
Test = "1.11.0"
=======
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Nucleus = "cd814215-3b54-4e50-ac5e-8a2c7852bc16"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[sources]
Nucleus = {path = "../Nucleus.jl"}

[compat]
DataFrames = "1.7.0"
>>>>>>> e7d0ed3 (unknown changes)
